name: InventoryLibs
main: m1rage\invlibs\Loader
version: 0.1.0
api: 5.41.0
load: STARTUP
authors: [m1rage, Muqsit]
description: InvMenu-based virtual inventory library for SleepPro Public.
website: https://github.com/SleepPro-Core-Minecraft-BE/InventoryLibs
